spring.application.name=EC-SITE
server.port=${PORT:8080}

# Supabase（PostgreSQL）
spring.datasource.url=postgresql://postgres:7GTE8hAOtTVbG3m5@db.ywezkilzisembcekepvb.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=7GTE8hAOtTVbG3m5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
