spring.application.name=EC-SITE
server.port=${PORT:8080}

# Supabase（PostgreSQL）
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ywezkilzisembcekepvb
spring.datasource.password=7GTE8hAOtTVbG3m5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true