spring.application.name=EC-SITE
server.port=${PORT:8080}

# Supabase（PostgreSQL）
spring.datasource.url=${postgresql://postgres:[YOUR-PASSWORD]@db.ywezkilzisembcekepvb.supabase.co:5432/postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=7GTE8hAOtTVbG3m5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
